# -*- coding: utf-8 -*-
"""part2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fYU2EFoE2SPScIcf3XLYufvzD-4Jt940

# problem 2

## code form the orignal example
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

import numpy as np
np.random.seed(42)

xs = 2 * np.random.rand(100, 1)
ys = 4 + 3 * xs + np.random.rand(100, 1)

plt.plot(xs, ys, "b.")
plt.xlabel("$x_1$", fontsize=18)
plt.ylabel("$y$", rotation=0, fontsize=18)
plt.axis([0, 2, 0, 15])
plt.show()

# split the data into training and test sets
# train set
train_xs = xs[:80]
train_ys = ys[:80]
# test set
test_xs = xs[80:]
test_ys = ys[80:]

"""# Linear regression using numpy"""

# number of epochs
epochs = 10
# learning rate
lr = 0.01

"""### create two diffrent weights"""

# initial value for weight w and bias b
w1 = np.random.randn(1)
b = np.zeros(1)
w2 = np.random.randn(1)

"""### y_hat =  w1 * x + w2 * x + bias"""

for epoch in np.arange(epochs):
  for i in np.arange(80):
    y_pred = w1 * train_xs[i] + w2 * train_xs[i] + b
    
    grad_w = (y_pred - train_ys[i]) * train_xs[i]
    grad_b = (y_pred - train_ys[i])
    
    w1 -= lr * grad_w
    w2 -= lr * grad_w
    b -= lr * grad_b

test_loss = 0
for i in np.arange(20):
  test_loss += 0.5 * (w1 * test_xs[i]+ w2 * test_xs[i] +  b - test_ys[i]) ** 2
test_loss /= 20

test_loss

pred_ys = w1 * test_xs + w2 * test_xs+  b

plt.plot(test_xs, test_ys, "b.")
plt.plot(test_xs, pred_ys, "r.") # predicted values
plt.xlabel("$x_1$", fontsize=18)
plt.ylabel("$y$", rotation=0, fontsize=18)
plt.axis([0, 2, 0, 15])
plt.show()

b

w

w2

