# -*- coding: utf-8 -*-
"""part3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YewozmnS4k2o2owFbwF7Gu-DKuR7lhcn

# problem 3
"""

from keras.datasets import mnist
import matplotlib.pyplot as plt
import numpy as np

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

"""## summing images of same label"""

imgArr = np.zeros((10,28,28))
sum = np.zeros((10))
for i in range(60000):
    imgArr[train_labels[i]] += train_images[i]
    sum[train_labels[i]] += 1

"""## displayed adverage image"""

for i in range(10):
  print(i)
  plt.imshow(imgArr[i]/sum[i])
  plt.show()

